numpy

In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.4 MB 9.1 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.4 MB 9.1 MB/s eta 0:00:01
   ------------------- -------------------- 6.0/12.4 MB 9.5 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.4 MB 10.0 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.4 MB 10.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 10.3 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 9.7 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
zeros = np.zeros((3, 5))

print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
ones = np.ones((2, 3))

print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 일련 번호로 만드는 배열

seq1 = np.arange(10)
seq2 = np.arange(1, 11, 2)

print(seq1)
print(seq2)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [9]:
# 지정된 시작 번호 끝 번호 이 사이를 동일한 간격으로 나눠주는 함수

linspace = np.linspace(1, 10, 4)

print(linspace)

[ 1.  4.  7. 10.]


In [10]:
list_temp = [
    [1, 2, 3],
    [4, 5, 6]
]

arr1 = np.array(list_temp)

In [24]:
print(arr1)
print(arr1.shape)           # 배열의 사이즈 반환 : (행, 열)
print(arr1.ndim)            # 배열의 차원 반환
print(arr1.size)            # 요소의 개수
print(arr1.dtype)           # 타입 확인

# 슬라이싱
print(arr1[:3])

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
[[1 2 3]
 [4 5 6]]


In [26]:
# 배열도 인덱싱과 슬라이싱이 가능 -> 리스트와 같다!

print(arr1)
# print(arr1[2])
# print(arr1[-1])
print(arr1[0], type(arr1[0]))
print(arr1[0][1])

[[1 2 3]
 [4 5 6]]
[1 2 3] <class 'numpy.ndarray'>
2


In [27]:
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
arr[0 : 2, 1:]

array([[2, 3],
       [5, 6]])

In [29]:
# 배열의 연산

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [34]:
print(arr1 + 10)
print(arr1 * 10)
print(arr1 ** 2)
print(arr1 + arr2)
print(arr1 * arr2)


[11 12 13]
[10 20 30]
[1 4 9]
[5 7 9]
[ 4 10 18]


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)

[1 2 3 4 5 6]


In [42]:
# 1차원 -> 2차원

reshaped_arr = arr.reshape(2, 3)

print(reshaped_arr)
print(reshaped_arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [43]:
# 2 -> 1

flat_arr = reshaped_arr.flatten()

print(flat_arr)

[1 2 3 4 5 6]


In [45]:
# 필터링

filter_arr = arr[arr > 3]

print(filter_arr)

[4 5 6]


In [46]:
# 난수로 배열 생성

ran_arr1 = np.random.rand(10)

print(ran_arr1)

[0.94327022 0.27427999 0.59879722 0.7916663  0.81769445 0.02653783
 0.30783851 0.61061901 0.62384005 0.45559045]


In [47]:
ran_arr2 = np.random.randint(1, 45, size=(5, 6))

print(ran_arr2)

[[39 40  5 14 42 39]
 [18 29  1 40 21  6]
 [29  5 30 28 17 15]
 [ 9 39  8 17 32  3]
 [ 4 10 14 35 24 26]]
